'use strict';
function cfOwner(){return S.user&&S.user.role==='owner'}
function cfVal(items,id,fallback=''){const x=(items||[]).find(v=>v.id===id);return x?x.value:fallback}
async function cfLoadZoneTools(zone){
 const host=$('#cfZoneTools');if(!host||!zone)return;host.innerHTML='<div class="empty">Memuat zone settings…</div>';
 try{const d=await api('/api/cloudflare-zone-settings?zone='+encodeURIComponent(zone));const items=d.items||[];
  host.innerHTML=`<div class="toolbar"><b>${esc(zone)}</b><span class="status on">Managed</span></div><div class="form-grid">
  <label>SSL/TLS<select id="cfSsl"><option value="strict">Full (strict)</option><option value="full">Full</option><option value="flexible">Flexible</option><option value="off">Off</option></select></label>
  <label>Always HTTPS<select id="cfHttps"><option value="on">On</option><option value="off">Off</option></select></label>
  <label>HTTPS Rewrites<select id="cfRewrite"><option value="on">On</option><option value="off">Off</option></select></label>
  <label>Brotli<select id="cfBrotli"><option value="on">On</option><option value="off">Off</option></select></label>
  <label>HTTP/3<select id="cfHttp3"><option value="on">On</option><option value="off">Off</option></select></label>
  <div style="align-self:end" class="actions">${cfOwner()?'<button class="btn" id="cfSaveZone">Simpan Settings</button><button class="btn secondary" id="cfPurge">Purge Cache</button>':'<span class="tiny muted">Owner only</span>'}</div></div>`;
  $('#cfSsl').value=cfVal(items,'ssl','strict');$('#cfHttps').value=cfVal(items,'always_use_https','on');$('#cfRewrite').value=cfVal(items,'automatic_https_rewrites','on');$('#cfBrotli').value=cfVal(items,'brotli','on');$('#cfHttp3').value=cfVal(items,'http3','on');
  if($('#cfSaveZone'))$('#cfSaveZone').onclick=async()=>{try{for(const [setting,el] of [['ssl','#cfSsl'],['always_use_https','#cfHttps'],['automatic_https_rewrites','#cfRewrite'],['brotli','#cfBrotli'],['http3','#cfHttp3']])await api('/api/cloudflare-zone-settings?zone='+encodeURIComponent(zone),{method:'PATCH',body:{setting,value:$(el).value}});toast('Cloudflare settings disimpan');cfLoadZoneTools(zone)}catch(e){toast(e.message,true)}};
  if($('#cfPurge'))$('#cfPurge').onclick=async()=>{if(!confirm('Purge seluruh cache '+zone+'?'))return;try{await api('/api/cloudflare-cache',{method:'POST',body:{zone,files:[]}});toast('Cloudflare cache dipurge')}catch(e){toast(e.message,true)}};
 }catch(e){host.innerHTML=`<div class="notice warn">${esc(e.message)}</div>`}
}
async function cfLoadRoutes(tunnelId){
 const host=$('#cfRoutes');if(!host||!tunnelId)return;host.innerHTML='<div class="empty">Memuat tunnel routes…</div>';
 try{const d=await api('/api/cloudflare-tunnel-routes?id='+encodeURIComponent(tunnelId));const rows=(d.items||[]).map(x=>`<tr><td data-label="Hostname"><b>${esc(x.hostname)}</b></td><td data-label="Service"><code>${esc(x.service)}</code></td><td data-label="TLS">${x.origin_request?.noTLSVerify?'<span class="status warn">No Verify</span>':'<span class="status on">Verify</span>'}</td><td class="actions">${cfOwner()?`<button class="btn secondary small" data-cfedit="${esc(x.hostname)}" data-service="${esc(x.service)}" data-notls="${x.origin_request?.noTLSVerify?'1':'0'}">Edit</button><button class="btn danger small" data-cfdel="${esc(x.hostname)}">Hapus</button>`:''}</td></tr>`).join('');
  host.innerHTML=`${cfOwner()?`<form id="cfRouteForm" class="form-grid"><input type="hidden" name="old_hostname"><label>Public Hostname<input name="hostname" placeholder="app.example.com" required></label><label class="wide">Origin Service<input name="service" value="https://127.0.0.1:443" required><span class="tiny muted">Contoh: https://127.0.0.1:443 atau http://127.0.0.1:9100</span></label><label><span>TLS Origin</span><select name="no_tls_verify"><option value="false">Verify certificate</option><option value="true">No TLS Verify</option></select></label><div style="align-self:end" class="actions"><button class="btn" id="cfRouteSubmit">Publish + Auto DNS</button><button type="button" class="btn secondary" id="cfRouteCancel" hidden>Batal</button></div></form>`:''}<div class="table-wrap"><table class="table"><thead><tr><th>Hostname</th><th>Origin</th><th>TLS</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Belum ada published route.</td></tr>'}</tbody></table></div>`;
  const f=$('#cfRouteForm');if(f){const reset=()=>{f.reset();f.elements.old_hostname.value='';f.elements.service.value='https://127.0.0.1:443';$('#cfRouteSubmit').textContent='Publish + Auto DNS';$('#cfRouteCancel').hidden=true};$('#cfRouteCancel').onclick=reset;f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f),old=x.get('old_hostname');try{await api('/api/cloudflare-tunnel-routes?id='+encodeURIComponent(tunnelId),{method:old?'PATCH':'POST',body:{tunnel_id:tunnelId,hostname:x.get('hostname'),old_hostname:old,service:x.get('service'),no_tls_verify:x.get('no_tls_verify')==='true',delete_dns:false}});toast(old?'Route diperbarui':'Route + DNS dibuat');cfLoadRoutes(tunnelId)}catch(z){toast(z.message,true)}}}
  host.onclick=async e=>{const edit=e.target.closest('[data-cfedit]'),del=e.target.closest('[data-cfdel]');if(edit&&f){f.elements.old_hostname.value=edit.dataset.cfedit;f.elements.hostname.value=edit.dataset.cfedit;f.elements.service.value=edit.dataset.service;f.elements.no_tls_verify.value=edit.dataset.notls==='1'?'true':'false';$('#cfRouteSubmit').textContent='Simpan Route';$('#cfRouteCancel').hidden=false;f.scrollIntoView({behavior:'smooth',block:'center'});return}if(del){if(!confirm('Hapus route dan DNS otomatis untuk '+del.dataset.cfdel+'?'))return;try{await api('/api/cloudflare-tunnel-routes?id='+encodeURIComponent(tunnelId),{method:'DELETE',body:{tunnel_id:tunnelId,hostname:del.dataset.cfdel,delete_dns:true}});toast('Route dan DNS dihapus');cfLoadRoutes(tunnelId)}catch(z){toast(z.message,true)}}};
 }catch(e){host.innerHTML=`<div class="notice warn">${esc(e.message)}</div>`}
}
async function xcCloudflare(c){
 const [cfg,zones,tunnels]=await Promise.all([api('/api/cloudflare'),api('/api/cloudflare-zones').catch(e=>({items:[],error:e.message})),api('/api/cloudflare-tunnels').catch(e=>({items:[],error:e.message}))]);
 const owner=cfOwner(),z=zones.items||[],ts=tunnels.items||[];S.cfZone=S.cfZone||cfg.zone_name||z[0]?.name||'';S.cfTunnel=S.cfTunnel||ts[0]?.id||'';
 const cap=cfg.capabilities||{};const pf=v=>v?'YES':(cap.permissions_visible?'NO':'UNKNOWN');const permStatus=`Token: ${cap.kind||'unknown'} · Auto Zone Control: ${cap.zone_control_ready?'READY':'SETUP'} · DNS Write: ${pf(cap.dns_write)} · Zone Write: ${pf(cap.zone_write)} · Tunnel Write: ${pf(cap.tunnel_write)}`;const conn=`<div class="grid metrics">${metric('Account',cfg.account_id||'Not set',cfg.configured?'Connected':'Setup required')}${metric('Zone',cfg.zone_name||'-','Auto Zone ID')}${metric('API Token',cfg.api_token_masked||'-',cfg.api_token_set?'Stored / fallback':'Missing')}${metric('R2',cfg.r2_configured?'Ready':'Not configured',cfg.access_key_id_masked||'-')}</div><div class="notice ${cap.dns_write&&cap.zone_write&&cap.tunnel_write?'good':'warn'}" style="margin-bottom:12px">${esc(permStatus)}<div class="tiny muted" style="margin-top:5px">Xshoter otomatis membuat token Zone berizin minimum saat Account API Token tidak membawa izin Zone/DNS. Tunnel tetap memakai izin Account Token.</div></div>${owner?`<form id="cfConfigForm" class="form-grid"><label>Account ID<input name="account_id" value="${esc(cfg.account_id||'')}" placeholder="Auto-detect if only one account"></label><label>Account API Token<input name="api_token" type="password" placeholder="${esc(cfg.api_token_masked||'Leave blank to keep current')}" autocomplete="new-password"></label><label>Default Zone<input name="zone_name" value="${esc(cfg.zone_name||'')}"></label><label>Default Tunnel<select name="tunnel_id"><option value="">Auto (if only one)</option>${ts.map(t=>`<option value="${esc(t.id)}" ${t.id===cfg.tunnel_id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>R2 Access Key ID<input name="access_key_id" type="password" placeholder="${esc(cfg.access_key_id_masked||'Optional')}" autocomplete="new-password"></label><label>R2 Secret Access Key<input name="secret_access_key" type="password" placeholder="Leave blank to keep current" autocomplete="new-password"></label><label>R2 API Endpoint<input name="api_endpoint" value="${esc(cfg.api_endpoint||'')}" placeholder="https://ACCOUNT.r2.cloudflarestorage.com"></label><div class="wide actions"><button type="button" class="btn secondary" id="cfTest">Test Connection</button><button class="btn">Save Securely</button></div></form><div id="cfTestResult"></div>`:'<div class="notice">Cloudflare credential hanya dapat diubah oleh Owner.</div>'}`;
 const zoneRows=z.map(x=>`<tr><td data-label="Domain"><b>${esc(x.name)}</b><div class="tiny muted">${esc(x.id)}</div></td><td data-label="Status"><span class="status ${x.status==='active'?'on':'warn'}">${esc(x.status)}</span></td><td data-label="Nameservers"><span class="tiny">${esc((x.name_servers||[]).join(' · ')||'-')}</span></td><td class="actions"><button class="btn secondary small" data-cfdns="${esc(x.name)}">DNS</button><button class="btn secondary small" data-cftools="${esc(x.name)}">Settings</button>${owner?`<button class="btn danger small" data-cfzone-del="${esc(x.id)}" data-name="${esc(x.name)}">Hapus</button>`:''}</td></tr>`).join('');
 const zoneBody=`${owner?'<form id="cfAddZone" class="form-grid"><label class="wide">Tambah Domain ke Cloudflare<input name="name" placeholder="example.com" required><span class="tiny muted">Zone dibuat otomatis. Untuk registrar eksternal, nameserver tetap harus diarahkan sekali ke nameserver Cloudflare yang ditampilkan.</span></label><div style="align-self:end"><button class="btn">Tambah Domain</button></div></form>':''}<div class="table-wrap"><table class="table"><thead><tr><th>Domain</th><th>Status</th><th>Nameservers</th><th>Aksi</th></tr></thead><tbody>${zoneRows||'<tr><td colspan="4">Tidak ada zone atau token belum memiliki akses.</td></tr>'}</tbody></table></div>`;
 const tunnelOpts=ts.map(x=>`<option value="${esc(x.id)}" ${x.id===S.cfTunnel?'selected':''}>${esc(x.name)} · ${esc(x.status||'unknown')}</option>`).join('');
 const tunnelBody=`${tunnels.error?`<div class="notice warn">${esc(tunnels.error)}</div>`:`<div class="toolbar"><select id="cfTunnelPick">${tunnelOpts}</select><span class="tiny muted">Published route otomatis membuat CNAME → &lt;tunnel-id&gt;.cfargotunnel.com.</span></div><div id="cfRoutes"></div>`}`;
 c.innerHTML=card('Cloudflare Account',conn)+card('Domains / Zones',zoneBody)+card('Zone Tools','<div id="cfZoneTools"></div>')+card('Cloudflare Tunnel',tunnelBody);
 if(owner){const f=$('#cfConfigForm'),body=()=>{const x=new FormData(f);return Object.fromEntries([...x.entries()])};f.onsubmit=async e=>{e.preventDefault();try{await api('/api/cloudflare',{method:'POST',body:body()});toast('Cloudflare credential disimpan');render('cloudflare')}catch(z){toast(z.message,true)}};$('#cfTest').onclick=async()=>{try{const d=await api('/api/cloudflare-test',{method:'POST',body:body()});const cp=d.capabilities||{};$('#cfTestResult').innerHTML=`<div class="notice ${d.account_ok&&d.zone_ok?'good':'warn'}" style="margin-top:12px">Account: ${d.account_ok?'OK':'FAIL'} · Zone: ${d.zone_ok?'OK':'FAIL'} · R2: ${d.r2_ok?'OK':(cfg.r2_configured?'FAIL':'Not tested')}<div class="tiny" style="margin-top:6px">Token ${esc(cp.kind||'unknown')} · DNS Write ${cp.permissions_visible?(cp.dns_write?'✓':'✕'):'?'} · Zone Write ${cp.permissions_visible?(cp.zone_write?'✓':'✕'):'?'} · Tunnel Write ${cp.permissions_visible?(cp.tunnel_write?'✓':'✕'):'?'}</div></div>`}catch(z){toast(z.message,true)}};
  const az=$('#cfAddZone');if(az)az.onsubmit=async e=>{e.preventDefault();const x=new FormData(az);try{const d=await api('/api/cloudflare-zones',{method:'POST',body:{name:x.get('name')}});const ns=(d.zone?.name_servers||[]).join(' , ');toast('Domain ditambahkan ke Cloudflare');if(ns)alert('Cloudflare nameservers:\n'+ns+'\n\nJika registrar domain berada di luar Cloudflare, arahkan nameserver domain ke nilai ini sekali.');render('cloudflare')}catch(z){toast(z.message,true)}};
 }
 c.onclick=async e=>{const dns=e.target.closest('[data-cfdns]'),tools=e.target.closest('[data-cftools]'),del=e.target.closest('[data-cfzone-del]');if(dns){S.cfZone=dns.dataset.cfdns;render('dns');return}if(tools){S.cfZone=tools.dataset.cftools;cfLoadZoneTools(S.cfZone);return}if(del){const name=del.dataset.name,confirmName=prompt('Ketik domain untuk menghapus zone Cloudflare:',name);if(confirmName!==name)return;try{await api('/api/cloudflare-zones?id='+encodeURIComponent(del.dataset.cfzoneDel),{method:'DELETE',body:{confirm:confirmName}});toast('Zone dihapus');render('cloudflare')}catch(z){toast(z.message,true)}}};
 if($('#cfTunnelPick'))$('#cfTunnelPick').onchange=e=>{S.cfTunnel=e.target.value;cfLoadRoutes(S.cfTunnel)};
 if(S.cfZone)cfLoadZoneTools(S.cfZone);if(S.cfTunnel)cfLoadRoutes(S.cfTunnel);
}
