'use strict';
async function xcSystem(c){
 const [s,q]=await Promise.all([api('/api/system'),api('/api/security-overview')]);
 c.innerHTML=`<div class="grid metrics">${metric('OS',s.os,s.arch)}${metric('Kernel',s.kernel,s.hostname)}${metric('PHP',s.php,'CLI')}${metric('Node',s.node,'runtime')}</div>`+
 card('Software',`<div class="row-list"><div class="row-item"><div class="row-main"><b>Nginx</b><span>${esc(s.nginx)}</span></div></div><div class="row-item"><div class="row-main"><b>MariaDB</b><span>${esc(s.mariadb)}</span></div></div></div>`)+
 card('Server Security',`<div class="notice good">SSH hardening</div><pre class="code">${esc((q.ssh||[]).join('\n'))}</pre><div class="notice" style="margin-top:12px">Fail2Ban</div><pre class="code">${esc(q.fail2ban||'')}</pre>`);
}
async function xcProcesses(c){
 const d=await api('/api/processes');
 const rows=d.items.map(x=>`<tr><td data-label="PID">${x.pid}</td><td data-label="User">${esc(x.user)}</td><td data-label="CPU">${x.cpu}%</td><td data-label="RAM">${x.memory}%</td><td data-label="Age">${Math.floor(x.seconds/60)}m</td><td data-label="Process"><b>${esc(x.command)}</b></td></tr>`).join('');
 c.innerHTML=card('Process Monitor',`<div class="toolbar"><span class="muted tiny">Top process berdasarkan CPU</span><button class="btn secondary small" id="procRefresh">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>PID</th><th>User</th><th>CPU</th><th>RAM</th><th>Age</th><th>Process</th></tr></thead><tbody>${rows}</tbody></table></div>`);
 $('#procRefresh').onclick=()=>render('processes');
}
async function xcUpdates(c){
 const d=await api('/api/packages');
 const rows=d.items.map(x=>`<tr><td data-label="Package"><b>${esc(x.name)}</b></td><td data-label="Installed">${esc(x.installed||'-')}</td><td data-label="Candidate">${esc(x.candidate)}</td><td class="actions">${canWrite()?`<button class="btn small" data-upkg="${esc(x.name)}">Upgrade</button>`:''}</td></tr>`).join('');
 c.innerHTML=card('Package Updates',`<div class="toolbar"><span class="muted tiny">Upgrade paket sistem secara individual. Perubahan tetap dicatat oleh Audit Log.</span>${canWrite()?'<button class="btn secondary small" id="aptRefresh">Refresh Repository</button>':''}</div><div class="table-wrap"><table class="table"><thead><tr><th>Package</th><th>Installed</th><th>Candidate</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Semua paket sudah terbaru.</td></tr>'}</tbody></table></div>`);
 if($('#aptRefresh'))$('#aptRefresh').onclick=async()=>{try{await api('/api/packages',{method:'POST',body:{action:'refresh',name:''}});toast('Repository diperbarui');render('updates')}catch(e){toast(e.message,true)}};
 c.onclick=async e=>{const b=e.target.closest('[data-upkg]');if(!b)return;if(!confirm(`Upgrade ${b.dataset.upkg}?`))return;try{await api('/api/packages',{method:'POST',body:{action:'upgrade',name:b.dataset.upkg}});toast('Package di-upgrade');render('updates')}catch(x){toast(x.message,true)}};
 }async function xcDNS(c){
 const d=await api('/api/dns');
 const form=canWrite()?`<form id="dnsForm" class="dns-form"><input type="hidden" name="id"><label>Type<select name="type"><option>A</option><option>AAAA</option><option>CNAME</option><option>TXT</option><option>MX</option></select></label><label>Name<input name="name" placeholder="@ atau subdomain" required></label><label class="dns-wide">Content<input name="content" placeholder="IP, hostname, atau value record" required></label><label>TTL<input name="ttl" type="number" value="1" min="1"></label><label>MX Priority<input name="priority" type="number" value="10" min="0" max="65535"><span class="tiny muted">Hanya digunakan untuk MX</span></label><label><span>Cloudflare Proxy</span><select name="proxied"><option value="true">Proxied</option><option value="false">DNS only</option></select></label><div class="dns-wide actions"><button class="btn" id="dnsSubmit">Tambah Record</button><button class="btn secondary" type="button" id="dnsCancel" hidden>Batal Edit</button></div></form>`:'';
 const records=d.items.map(x=>`<article class="dns-record"><div class="dns-record-top"><div class="dns-ident"><span class="dns-type">${esc(x.type)}</span><div><b class="dns-name">${esc(x.name)}</b><span class="dns-ttl">TTL ${esc(x.ttl||'Auto')}${x.type==='MX'&&x.priority!=null?' · Priority '+esc(x.priority):''}</span></div></div><span class="status ${x.proxied?'on':'warn'}">${x.proxied?'Proxied':'DNS only'}</span></div><div class="dns-value"><span>Content</span><code>${esc(x.content)}</code></div>${canWrite()?`<div class="dns-actions"><button class="btn secondary small" data-dnsedit="${esc(x.id)}" data-type="${esc(x.type)}" data-name="${esc(x.name)}" data-content="${esc(x.content)}" data-ttl="${esc(x.ttl||1)}" data-priority="${esc(x.priority||10)}" data-proxied="${x.proxied?'true':'false'}">Edit</button><button class="btn danger small" data-dnsdel="${esc(x.id)}">Hapus</button></div>`:''}</article>`).join('');
 c.innerHTML=card('Cloudflare DNS',form||'<div class="notice">Read-only.</div>')+card('DNS Records',`<div class="dns-summary"><span>${d.items.length} record</span><span class="muted tiny">${esc(d.zone||'')}</span></div><div class="dns-list">${records||'<div class="empty">Belum ada DNS record.</div>'}</div>`);
 const f=$('#dnsForm');const reset=()=>{if(!f)return;f.reset();f.elements.id.value='';f.elements.ttl.value='1';f.elements.priority.value='10';$('#dnsSubmit').textContent='Tambah Record';$('#dnsCancel').hidden=true};if($('#dnsCancel'))$('#dnsCancel').onclick=reset;
 if(f)f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f);const id=x.get('id');const body={type:x.get('type'),name:x.get('name'),content:x.get('content'),ttl:Number(x.get('ttl')||1),priority:Number(x.get('priority')||10),proxied:x.get('proxied')==='true'};try{await api('/api/dns'+(id?'?id='+encodeURIComponent(id):''),{method:id?'PATCH':'POST',body});toast(id?'DNS record diperbarui':'DNS record dibuat');render('dns')}catch(z){toast(z.message,true)}};
 c.onclick=async e=>{const edit=e.target.closest('[data-dnsedit]'),del=e.target.closest('[data-dnsdel]');if(edit&&f){f.elements.id.value=edit.dataset.dnsedit;f.elements.type.value=edit.dataset.type;f.elements.name.value=edit.dataset.name;f.elements.content.value=edit.dataset.content;f.elements.ttl.value=edit.dataset.ttl||1;f.elements.priority.value=edit.dataset.priority||10;f.elements.proxied.value=edit.dataset.proxied||'false';$('#dnsSubmit').textContent='Simpan Perubahan';$('#dnsCancel').hidden=false;f.scrollIntoView({behavior:'smooth',block:'start'});return}if(del){if(!confirm('Hapus DNS record ini?'))return;try{await api('/api/dns?id='+encodeURIComponent(del.dataset.dnsdel),{method:'DELETE',body:{}});toast('DNS record dihapus');render('dns')}catch(z){toast(z.message,true)}}};
}

async function xcSSL(c){
 const w=await api('/api/websites');const states=await Promise.all(w.items.map(async x=>{try{return {...x,status:await api('/api/ssl-status?domain='+encodeURIComponent(x.domain))}}catch{return {...x,status:{installed:false}}}}));
 const rows=states.map(x=>{const edge=x.status.mode==='cloudflare';const label=edge?'Cloudflare Edge':(x.status.installed?'Local TLS':'Not installed');return `<tr><td data-label="Domain"><b>${esc(x.domain)}</b></td><td data-label="Managed"><span class="status ${x.managed?'on':'warn'}">${x.managed?'Managed':'External'}</span></td><td data-label="SSL"><span class="status ${x.status.installed?'on':'warn'}">${label}</span></td><td data-label="Expires"><span class="tiny">${esc(x.status.expires||'-')}</span></td><td class="actions">${x.managed&&canWrite()&&!edge?`<button class="btn small" data-issue="${esc(x.domain)}">Issue / Renew</button>`:(edge?'<span class="tiny muted">Managed at Cloudflare edge</span>':'')}</td></tr>`}).join('');
 c.innerHTML=card('SSL Certificates',`<div class="notice good" style="margin-bottom:12px">Domain yang diproxy melalui Cloudflare menggunakan Edge TLS dan tidak memerlukan sertifikat Let’s Encrypt lokal.</div><div class="table-wrap"><table class="table"><thead><tr><th>Domain</th><th>Status</th><th>SSL</th><th>Expires</th><th>Aksi</th></tr></thead><tbody>${rows}</tbody></table></div>`);
 c.onclick=async e=>{const b=e.target.closest('[data-issue]');if(!b)return;if(!confirm(`Issue/Renew SSL ${b.dataset.issue}?`))return;try{await api('/api/ssl',{method:'POST',body:{domain:b.dataset.issue,email:''}});toast('SSL selesai diproses');render('ssl')}catch(z){toast(z.message,true)}};
}
async function xcWebLogs(c){
 const w=await api('/api/websites');const domain=S.webLogDomain||w.items[0]?.domain||'';const type=S.webLogType||'access';if(!domain){c.innerHTML=card('Website Logs','<div class="empty">Belum ada website.</div>');return}const d=await api(`/api/web-logs?domain=${encodeURIComponent(domain)}&type=${encodeURIComponent(type)}`);
 c.innerHTML=card('Website Logs',`<div class="toolbar"><select id="wlDomain">${w.items.map(x=>`<option ${x.domain===domain?'selected':''}>${esc(x.domain)}</option>`).join('')}</select><select id="wlType"><option ${type==='access'?'selected':''}>access</option><option ${type==='error'?'selected':''}>error</option></select><button class="btn secondary small" id="wlRefresh">Refresh</button></div><pre class="logbox">${esc(d.text||'')}</pre>`);
 $('#wlDomain').onchange=e=>{S.webLogDomain=e.target.value;render('weblogs')};$('#wlType').onchange=e=>{S.webLogType=e.target.value;render('weblogs')};$('#wlRefresh').onclick=()=>render('weblogs');
}async function xcPHP(c){
 const w=await api('/api/websites');const managed=w.items.filter(x=>x.managed&&x.php_configurable);const domain=S.phpDomain||managed[0]?.domain||'';if(!domain){c.innerHTML=card('PHP Settings','<div class="notice warn">Belum ada website dengan PHP-FPM pool yang dapat dikonfigurasi.</div>');return}const d=await api('/api/php-settings?domain='+encodeURIComponent(domain));const v=d.settings||{};
 c.innerHTML=card('PHP Settings',`<div class="toolbar"><select id="phpDomain">${managed.map(x=>`<option ${x.domain===domain?'selected':''}>${esc(x.domain)}</option>`).join('')}</select><span class="status on">PHP ${esc(d.version)}</span></div>${canWrite()?`<form id="phpForm" class="form-grid"><label>memory_limit<input name="memory_limit" value="${esc(v.memory_limit||'256M')}" required></label><label>upload_max_filesize<input name="upload_max_filesize" value="${esc(v.upload_max_filesize||'128M')}" required></label><label>post_max_size<input name="post_max_size" value="${esc(v.post_max_size||'128M')}" required></label><label>max_execution_time<input name="max_execution_time" type="number" value="${esc(v.max_execution_time||'120')}" required></label><label>max_input_vars<input name="max_input_vars" type="number" value="${esc(v.max_input_vars||'3000')}" required></label><div style="align-self:end"><button class="btn">Simpan & Reload FPM</button></div></form>`:'<div class="notice">Read-only.</div>'}`);
 $('#phpDomain').onchange=e=>{S.phpDomain=e.target.value;render('php')};const f=$('#phpForm');if(f)f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f);try{await api('/api/php-settings',{method:'POST',body:{domain,memory_limit:x.get('memory_limit'),upload_max_filesize:x.get('upload_max_filesize'),post_max_size:x.get('post_max_size'),max_execution_time:Number(x.get('max_execution_time')),max_input_vars:Number(x.get('max_input_vars'))}});toast('PHP settings disimpan');render('php')}catch(z){toast(z.message,true)}};
}
async function xcBackups(c){
 const [b,w,d]=await Promise.all([api('/api/backups'),api('/api/websites'),api('/api/databases')]);const webOpts=w.items.map(x=>`<option>${esc(x.domain)}</option>`).join(''),dbOpts=d.items.map(x=>`<option>${esc(x.name)}</option>`).join('');
 const tools=canWrite()?`<div class="form-grid"><label>Website<select id="bakWeb">${webOpts}</select></label><div style="align-self:end"><button class="btn" id="doBakWeb">Backup Website</button></div><label>Database<select id="bakDb">${dbOpts}</select></label><div style="align-self:end"><button class="btn" id="doBakDb">Backup Database</button></div></div>`:'';
 const rows=b.items.sort((a,z)=>new Date(z.time)-new Date(a.time)).map(x=>`<tr><td data-label="Backup"><b>${esc(x.file||x.name)}</b><div class="tiny muted">${esc(x.name)}</div></td><td data-label="Scope"><span class="status ${x.scope==='production'?'on':''}">${esc(x.scope||'manual')}</span></td><td data-label="Type">${esc(x.type||'archive')}</td><td data-label="Target">${esc(x.target||'-')}</td><td data-label="Size">${bytes(x.size)}</td><td data-label="Created">${new Date(x.time).toLocaleString(window.XCI18N?.locale?.()||'id-ID')}</td><td class="actions">${canWrite()&&x.restorable?`<button class="btn secondary small" data-restore="${esc(x.name)}">Restore</button>`:''}${canWrite()?`<button class="btn danger small" data-delbak="${esc(x.name)}">Hapus</button>`:''}</td></tr>`).join('');
 c.innerHTML=card('Buat Backup',tools||'<div class="notice">Read-only.</div>')+card('Backup Archives',`<div class="notice good" style="margin-bottom:12px">Backup production dan system ditampilkan dari storage Xshoter. Restore otomatis hanya tersedia untuk database dan website.</div><div class="table-wrap"><table class="table"><thead><tr><th>Backup</th><th>Scope</th><th>Type</th><th>Target</th><th>Size</th><th>Created</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Belum ada backup</td></tr>'}</tbody></table></div>`);
 if($('#doBakWeb'))$('#doBakWeb').onclick=()=>makeBackup('website',$('#bakWeb').value);if($('#doBakDb'))$('#doBakDb').onclick=()=>makeBackup('database',$('#bakDb').value);
 c.onclick=async e=>{const r=e.target.closest('[data-restore]');const d=e.target.closest('[data-delbak]');try{if(r){if(!confirm(`Restore ${r.dataset.restore}? Data saat ini dapat tertimpa.`))return;await api('/api/backup-actions',{method:'POST',body:{file:r.dataset.restore}});toast('Restore selesai');render('backups');return}if(d){if(!confirm(`Hapus backup ${d.dataset.delbak}?`))return;await api('/api/backup-actions?name='+encodeURIComponent(d.dataset.delbak),{method:'DELETE',body:{}});toast('Backup dihapus');render('backups')}}catch(x){toast(x.message,true)}};
}
async function xcFiles(c){
 if(!S.websites.length){const d=await api('/api/websites');S.websites=d.items}if(!S.fileRoot&&S.websites[0]){S.fileRoot=S.websites[0].root;S.filePath=S.fileRoot}const opts=S.websites.map(x=>`<option value="${esc(x.root)}" ${x.root===S.fileRoot?'selected':''}>${esc(x.domain)}</option>`).join('');if(!S.filePath){c.innerHTML=card('File Manager','<div class="empty">Belum ada website.</div>');return}
 const d=await api('/api/files?path='+encodeURIComponent(S.filePath));if(!d.items){c.innerHTML=card('Edit File',`<div class="toolbar"><button class="btn secondary small" id="fileBack">← Kembali</button><span class="tiny muted">${esc(d.path)}</span></div><textarea id="editor" class="code" style="min-height:60vh">${esc(d.content)}</textarea>${canWrite()?'<div class="actions" style="margin-top:10px"><button class="btn" id="saveFile">Simpan</button><button class="btn secondary" id="renameFile">Rename</button><button class="btn danger" id="deleteFile">Hapus</button></div>':''}`);$('#fileBack').onclick=()=>{S.filePath=pathParent(S.filePath);render('files')};if($('#saveFile'))$('#saveFile').onclick=async()=>{try{await api('/api/files',{method:'POST',body:{path:S.filePath,content:$('#editor').value}});toast('File disimpan')}catch(z){toast(z.message,true)}};if($('#renameFile'))$('#renameFile').onclick=()=>xcRenamePath(S.filePath);if($('#deleteFile'))$('#deleteFile').onclick=()=>xcDeletePath(S.filePath);return}
 const rel=S.filePath.slice(S.fileRoot.length)||'/';const list=d.items.map(x=>{const p=S.filePath.replace(/\/$/,'')+'/'+x.name;return `<div class="file"><button class="ghost" data-open="${esc(p)}" style="padding:0">${x.dir?'📁':'📄'}</button><button class="ghost file-name" data-open="${esc(p)}" style="text-align:left">${esc(x.name)}</button><span class="tiny muted">${x.dir?'Folder':bytes(x.size)}</span>${canWrite()?`<button class="btn secondary small" data-rename="${esc(p)}">Rename</button><button class="btn danger small" data-delete="${esc(p)}">Hapus</button>`:''}</div>`}).join('');
 c.innerHTML=card('File Manager',`<div class="toolbar"><select id="sitePick">${opts}</select><div class="right"><button class="btn secondary small" id="fileUp">Naik</button>${canWrite()?'<label class="btn secondary small upload-pick">Upload<input id="uploadFiles" type="file" multiple hidden></label><button class="btn secondary small" id="newFolder">Folder Baru</button><button class="btn small" id="newFile">File Baru</button>':''}</div></div><div class="notice" style="margin-bottom:10px">${esc(rel)}</div><div class="file-list">${list||'<div class="empty">Folder kosong</div>'}</div>`);
 $('#sitePick').onchange=e=>{S.fileRoot=e.target.value;S.filePath=e.target.value;render('files')};$('#fileUp').onclick=()=>{if(S.filePath!==S.fileRoot){S.filePath=pathParent(S.filePath);if(!S.filePath.startsWith(S.fileRoot))S.filePath=S.fileRoot;render('files')}};if($('#uploadFiles'))$('#uploadFiles').onchange=e=>xcUploadFiles(e.target);if($('#newFolder'))$('#newFolder').onclick=()=>xcCreatePath('mkdir');if($('#newFile'))$('#newFile').onclick=()=>xcCreatePath('touch');
 c.onclick=e=>{const o=e.target.closest('[data-open]'),r=e.target.closest('[data-rename]'),d=e.target.closest('[data-delete]');if(o){S.filePath=o.dataset.open;render('files');return}if(r)xcRenamePath(r.dataset.rename);if(d)xcDeletePath(d.dataset.delete)};
}
async function xcCreatePath(action){const name=prompt(action==='mkdir'?'Nama folder baru:':'Nama file baru:');if(!name||name.includes('/')||name==='.'||name==='..')return;const p=S.filePath.replace(/\/$/,'')+'/'+name;try{await api('/api/file-actions',{method:'POST',body:{action,path:p,target:''}});toast(action==='mkdir'?'Folder dibuat':'File dibuat');render('files')}catch(e){toast(e.message,true)}}
async function xcRenamePath(src){const old=src.split('/').pop(),name=prompt('Nama baru:',old);if(!name||name.includes('/')||name===old)return;const dst=pathParent(src)+'/'+name;try{await api('/api/file-actions',{method:'POST',body:{action:'rename',path:src,target:dst}});if(S.filePath===src)S.filePath=dst;toast('Berhasil di-rename');render('files')}catch(e){toast(e.message,true)}}
async function xcDeletePath(p){if(!confirm(`Hapus ${p.split('/').pop()}?`))return;try{await api('/api/file-actions',{method:'POST',body:{action:'delete',path:p,target:''}});if(S.filePath===p)S.filePath=pathParent(p);toast('Dihapus');render('files')}catch(e){toast(e.message,true)}}
async function xcUploadFiles(input){
 const files=[...(input.files||[])];if(!files.length)return;
 try{for(let i=0;i<files.length;i++){const f=files[i];if(!f.name||f.name.includes('/')||f.name.includes('\\'))throw new Error('Nama file tidak valid');toast(`Upload ${i+1}/${files.length}: ${f.name}`);const p=S.filePath.replace(/\/$/,'')+'/'+f.name;const r=await fetch('/api/upload?path='+encodeURIComponent(p),{method:'POST',headers:{'x-csrf-token':S.csrf,'content-type':'application/octet-stream'},credentials:'same-origin',body:f});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Upload gagal (${r.status})`) }toast(`${files.length} file berhasil di-upload`);render('files')}catch(e){toast(e.message,true)}finally{input.value=''}
}
